version: '3.8'

services:
  # ==========================================
  # 1. EMPLOYEE SERVICE (DIMAS)
  # ==========================================
  employee-service:
    build:
      context: ./employee-service/employee-service
      dockerfile: Dockerfile
    container_name: employee-service
    ports:
      - "8001:8000"
    env_file:
      - ./employee-service/employee-service/.env
    depends_on:
      employee-db:
        condition: service_healthy
    networks:
      - shared-network

  employee-db:
    image: mysql:8.4
    container_name: employee-db
    environment:
      MYSQL_DATABASE: employee_service
      MYSQL_USER: employee_user
      MYSQL_PASSWORD: employee_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "33061:3306"
    volumes:
      - employee-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

  # ==========================================
  # 2. ABSENSI SERVICE (DYLAN)
  # ==========================================
  absensi-service:
    build:
      context: "./Absensi Service/dylan"
      dockerfile: Dockerfile
    container_name: absensi-service
    restart: unless-stopped
    ports:
      - "8002:80"
    env_file:
      - "./Absensi Service/dylan/.env"
    depends_on:
      absensi-db:
        condition: service_healthy
    networks:
      - shared-network

  absensi-db:
    image: postgres:15-alpine
    container_name: absensi-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: absensi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - absensi_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d absensi_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

  # ==========================================
  # 3. PAYROLL SERVICE (FARHAN)
  # ==========================================
  payroll-service:
    build:
      context: ./Payroll-Service/102022400032-M-farhan-chanafi-Payroll-Service
      dockerfile: Dockerfile
    container_name: payroll-service
    ports:
      - "8003:8000"
    volumes:
      - ./Payroll-Service/102022400032-M-farhan-chanafi-Payroll-Service:/app
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite
      - IAE_KEY=102022400032
      - EMPLOYEE_SERVICE_URL=http://employee-service:8000
      - EMPLOYEE_SERVICE_KEY=102022400197
      - ABSENSI_SERVICE_URL=http://absensi-service:80
      - ABSENSI_SERVICE_KEY=102022400074
      - IAE_CLOUD_URL=https://iae-sso.virtualfri.id
      - IAE_CLOUD_API_KEY=KEY-MHS-116
      - TEAM_ID=TEAM-10
    networks:
      - shared-network

volumes:
  employee-db-data:
  absensi_db_data:

networks:
  shared-network:
    driver: bridge
